### ISSUE TITLE
limit maximum number of rows for dataframes being read in

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#11]

**Comment by clnsmth** [comment]
I suggest this be an optional argument rather than an arbitrary limit to number of rows that can be read in. If performance and wait times are a concern for users, we could address this issue by supplying the user with a status bar (which has proven difficult to do) or inform the user of limitations through an expectation matrix ([suggested here](https://github.com/IMCR-Hackathon/ggplotgui/issues/18#issuecomment-502468397)) in the package documentation.

**Comment by clnsmth** [comment]
This conversation has moved to #44
