### ISSUE TITLE
break functions into separate files and put them in the R directory

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#17]
think about consistent naming conventions too

**Comment by clnsmth** [comment]
Hi @atn38, what is the status of atomizing the static report functions? I'm happy to lend a hand if you need one.

**Comment by atn38** [comment]
Hello @clnsmth,

The hackathon's nature makes it so that the functions written by static team are by themselves quite atomized already! 😋 

Ultimately, we should export two functions. It would be nice if users can use them from within the R pkg independent of the GUI. Names, of course, might change.

- `make_var_report`: my hope is that once the user has chosen a data entity, the GUI will include a dropdown menu to select a variable from the entity, then the GUI will pass that as the argument to this function, which then outputs a variable-level report suitable for display within the GUI itself.

- `make_entity_report`: this is what the GUI will call once the user clicks on the "download complete report" button. Takes an entity-level metajam output, outputs .html file. 

Functions written by static team will be absorbed into either of those two after some refactoring and renaming. I hope that's okay @jhp7e @alesiahallmark @CoastalPlainSoils!!

**Comment by clnsmth** [comment]
Thanks for this update @atn38. 

We all agree that `make_var_report()` and `make_entity_report()` will be accessible to users from within the R pkg independent of the GUI.

My understanding is that we agreed to add the GUI feature you suggest by `make_var_report()` as an enhancement once the core objectives of the project have been completed. I.e. the full static report and the interactive GUI in it's current configuration, and a fully tested, robust, and functioning R package.

In addition to exporting `make_var_report()` and `make_entity_report()`, we should also be exporting all the functions that `make_var_report()` and `make_entity_report()` wrap (except anonymous functions). Export by including `#' @export` in the `roxygen2` metadata block of each function. 

For ease of navigation and editing, we decided all functions should be added to the `/R` directory as separate .R files. I'm available to help with this if you need.

**Comment by atn38** [comment]
Hello @clnsmth, 

Thank you for the offer! I think the main files containing multiple functions to break up would be `/R/data_entity_summary.R`, `/R/data_variable_report.R`, and `/R/time_detective.R`. If you can take a look that'd be great.

**Comment by clnsmth** [comment]
OK @atn38. I'll get to work on this tomorrow.

**Comment by clnsmth** [comment]
Hi @atn38, in which branch of the project repo should I conduct this work? Thanks!

**Comment by atn38** [comment]
Hi Colin, I've been meaning to ask, thanks for reminding me! I can open a
merge request from dev_summary_report into master so you can do things
there. Would that work?

**Comment by clnsmth** [comment]
Sure @atn38. I'll wait until you've made that merge and I'll begin work soon thereafter.

**Comment by clnsmth** [comment]
@atn38, if created individual .R files for each function listed in `data_entity_summary.R, ` `data_variable_report.R` and `time_detective.R`, ensured I updated any calls to these 3 files in the code base, then deleted them. I've added `roxygen2` metadata blocks as placeholder headers to each function file. Please work with your group to complete these metadata.

@wetlandscapes, does your group have functions to break into separate files?
