### ISSUE TITLE
data ingest into edi shiny app

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#3]

**Comment by wetlandscapes** [comment]
As of ab8dac2645f39a76ece0bcf1deee83fdcb4c4c6e, there is now basic data ingestion functionality. There are still a number of issues that need to be fixed, though:

- Keep app from downloading data package if it is the same doi link that was already downloaded.
- Add some control flow for dealing with empty doi input. Causes app to crash if the doi is empty.
- Check what happens if the doi is inappropriate

**Comment by clnsmth** [comment]
@wetlandscapes, for the first issue _Keep app from downloading data package if it is the same doi link that was already downloaded._ do you mean download to R's temporary directory or to a local directory on a users computer?

I'll draft a function to address issues 2 and 3 for your review. What would you like the output of this function to be?

**Comment by wetlandscapes** [comment]
I mean someone might accidentally hit the "Fetch Data" button when they've not updated the doi. So, rather than download the package again, which can take a while, it would make more sense to just return the existing object already loaded in the app.

**Comment by clnsmth** [comment]
@wetlandscapes, this is how I plan to handle each of the above issues:

1.) Add logic to `data_package_download()` to skip download if the data package already exists in the temporary or user specified directory.

2.) Add logic to `data_package_read()` so when an empty character string (i.e. '') is input to the `data.pkg.doi` the function reads the data package from the temporary directory and returns an error if no data package is found.

3.) Add DOI validation check to `data_package_download()` and issue an error if the DOI syntax is wrong. Or do you want a different output if the user specifies a malformed DOI?

How does this sound to you @wetlandscapes?

**Comment by wetlandscapes** [comment]
@clnsmth 
1. Rather than add the logic to `data_package_download`, I made a wrapper for the function: `data_package_download_wrapper`. However, it is pretty ugly right now, because I was figuring out how to deal with "reactive" and "isolated" variables in shiny. This means the logic is split between the function and the app. I will try to clean-up my mess in the next day or two.

2. I've already integrated this logic into the wrapper function and app. It simply returns the existing list (generated from `data_package_download`), so no need to reprocess, making the whole thing a bit faster.

3. I've implemented a tryCatch, but it still needs a bit of work. Basically, if `package_download_wrapper` generates an error, it will return the example data set (located in `data\data_example.rda`). I'm going to update the wrapper function so that it will simply return which ever data package is currently loaded if an error is thrown.

Sorry I didn't say I'd be working on this. I wasn't sure if I'd have the time, but I figured it out today, after working on it for a while on Sunday. The key was better understanding how `shiny::isolate` works in the reactive context.

**Comment by wetlandscapes** [comment]
Well crap. I've been using `read_data_archived` in my wrapper and just tried to switch over to `data_package_download` and the app no longer works as expected, so I'm going to have to dig into that, as well.

**Comment by clnsmth** [comment]
Sorry for throwing that wrench into the machinery @wetlandscapes. Let me know if you need a briefing on it or want me to revise the functions. A couple changes to the `data_package_read()` that may produce the errors you're encountering:

1.) The output is of class 'list', not 'online_data'. I can change it back, but figured the 'online_data' was not very accurate since the source could be online or offline.

2.) The output list no longer contains the paths to each data object directory created by `data_package_download()`

**Comment by sheilasaia** [comment]
@wetlandscapes and @clnsmth, let me know if and how I can help with this! if it's fixed, maybe we can close the issue?

**Comment by wetlandscapes** [comment]
Oh, yeah, I updated the code I was using and forgot to mention it here. So, yes, this is done.
