### ISSUE TITLE
make edi doi entry conditional - shows up on "raw_data" tab only

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/ggplotgui#31]

**Comment by CoastalPlainSoils** [comment]
Question about related to data on the website/app....._(And I apologize if this was already discussed on the call the other day, my apologies I had a meeting come up during that time)._ So in using the app, the user has the option to upload a dataset... what if this dataset is preliminary results of a experiment and that the user just wants to use the EDI tool to observe these preliminary results and the user is sensitive to sharing that data since the results have not been published, etc. **Does the tool in any way store or any transmit data uploaded to it**? (Apart from the results provided to the user at the users request only). I think this would be an important item to address and disclose on the app.

**Comment by sheilasaia** [comment]
@CoastalPlainSoils yep, we want to enable the user to upload data too. three options for datasets are (1) use a sample dataset, (2) put in a doi and look at the associated datasets, (3) upload a text file. Does that sound ok? Let @wetlandscapes and I know if you have any other ideas.

**Comment by clnsmth** [comment]
Interesting question @CoastalPlainSoils. Regardless of where the app is deployed (from a users local machine or on a web-server) the current configuration stores the data in a temporary environment within R that is cleared each time a new dataset is loaded or when the app shuts down after a users session. However, the code is open source so if someone wanted to maliciously harvest a users data (server scenario above) they could __BUT__ data in and of itself isn't useful without metadata and in the "exploring unpublished data" use-case you mention above, the user wouldn't be uploading any metadata so the evildoer wouldn't have the necessary context to do anything productive with the data. Furthermore, if this is a concern the user can just run the app from their own computer without uploading anything to a server.
